export const CHECK_LOGIN="CHECK_LOGIN"
export const GET_MOVIES="GET_MOVIES"
export const GET_THEATRES="GET_THEATRES"
export const GET_SCREENINGS="GET_SCREENINGS"
export const GET_SCREENING="GET_SCREENING"
export const GET_SEATS="GET_SEATS"
//  Admin

export const GET_ADMIN_ERRORS="GET_ADMIN_ERRORS";
export const GET_ADMIN_MOVIES="GET_ADMIN_MOVIES";
export const UPDATE_ADMIN_MOVIE="UPDATE_ADMIN_MOVIE";
export const DELETE_ADMIN_MOVIE="DELTE_ADMIN_MOVIE";

export const GET_ADMIN_SCREENINGS="GET_ADMIN_SCREENINGS";
export const UPDATE_ADMIN_SCREENING="UPDATE_ADMIN_SCREENING";
export const DELETE_ADMIN_SCREENING="DELTE_ADMIN_SCREENING";

export const GET_ADMIN_USERS="GET_ADMIN_USERS";
export const DELETE_ADMIN_USER="DELETE_ADMIN_USER";
export const GET_SEAT_BOOKINGS="GET_SEAT_BOOKINGS";